import { Metadata, NextPage } from "next";
import Link from "next/link";
import { ReactElement } from "react";
import { Post } from "types/Post";
import styles from 'app/blog/page.module.scss';

export const metadata: Metadata = {
  title: 'Blog | Next App',
  description: 'Generated by create next app',
}

const baseURL = process.env.NEXT_PUBLIC_API_BASE_URL;

async function getPosts(): Promise<Post[]> {
  const result = await fetch(`${baseURL}/posts`, {
    next: {
      revalidate: 60
    }
  });

  if (!result.ok) {
    throw new Error('Unable to fetch posts!');
  }

  return result.json();
}

const Blog = async (): Promise<ReactElement>=> {
  const posts = await getPosts();

  return (
    <div className={styles.wrapper}>
      <h1 className={styles.title}>
        Blog
      </h1>
      <ul className={styles.postsList}>
        {posts.map((post) => {
          const {id, title } = post;
          return (
            <li key={id} className={styles.postsListItem}>
              <Link className={styles.postsListItemLink} href={`/blog/${id}`}>
                {title}
              </Link>
            </li>
            )
        })}
      </ul>
    </div>
  );
};

export default Blog;
