import { Metadata } from 'next';
import { ReactElement } from 'react';
import { Posts } from 'components/Posts';
import { PostsSearch } from 'components/PostsSearch';
import styles from 'app/blog/page.module.scss';

export const metadata: Metadata = {
  title: 'Blog | Next App',
  description: 'Generated by create next app',
}

const Blog =(): ReactElement => {
  return (
    <div className={styles.wrapper}>
      <h1 className={styles.title}>
        Blog
      </h1>
      <div className={styles.postsSearchWrapper}>
        <PostsSearch />
      </div>
      <Posts />
    </div>
  );
};

export default Blog;
