import { Metadata, NextPage } from "next";
import { ReactElement } from "react";
import styles from 'app/about/page.module.scss';

export const metadata: Metadata = {
  title: 'About | Next App',
  description: 'Generated by create next app',
}

const About: NextPage = (): ReactElement => {
  return (
    <h3 className={styles.title}>Select subitem</h3>
  )
}

export default About;
