import { Metadata } from 'next'
import './globals.scss'
import { Inter, Roboto } from 'next/font/google';
import { Footer } from 'components/Footer';
import { Header } from 'components/Header';
import { Providers } from 'store/provider';
import styles from 'app/layout.module.scss';

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
  style: 'normal'
});

export const metadata: Metadata = {
  title: 'Next Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  modal
}: {
  children: React.ReactNode,
  modal: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        <main className={styles.main}>
          <Providers>
            {modal}
            {children}
          </Providers>
        </main>
        <Footer />
      </body>
    </html>
  )
}
