'use client';

import { ReactElement } from 'react';
import Link from 'next/link';
import styles from 'app/not-found.module.scss';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Blog | Next App',
  description: 'Generated by create next app',
}

const NotFound = (): ReactElement => (
  <>
    <meta content='the requested page has not been found' name='description'/>
    <title>Not Found | Next App</title>
    <div className={styles.wrapper}>
      <h2 className={styles.title}>The requested page hasn&apos;t been found</h2>
      <p className={styles.detailedInfo}>
        Please go back to <Link className={styles.link} href="/">safety</Link>
      </p>
    </div>
  </>
);

export default NotFound;
