import { Metadata } from 'next';
import { ReactElement } from 'react';
import PostsServiceAxios from 'services/PostsServiceAxios';
import Link from 'next/link';
import styles from 'app/blogStatic/page.module.scss';

export const metadata: Metadata = {
  title: 'BlogStatic | Next App',
  description: 'Generated by create next app',
}

export const revalidate = 100000;

const Blog = async (): Promise<ReactElement> => {
  const posts = await PostsServiceAxios.getPosts();

  return (
    <div className={styles.wrapper}>
      <h1 className={styles.title}>
        Blog
      </h1>
      <ul className={styles.postsList}>
        {
          posts.map((post) => {
            const { id, title } = post;

            return (
              <li className={styles.postsListItem} key={id}>
                <Link className={styles.postsListItemLink} href={`/blogStatic/${id}`}>
                  {title}
                </Link>
              </li>
            )
          })
        }
      </ul>
    </div>
  );
}

export default Blog;
